---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-feature-discovery
  name: node-feature-discovery
spec:
  selector:
    matchLabels:
      app: node-feature-discovery
  template:
    metadata:
      labels:
        app: node-feature-discovery
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ravielluri/node_discovery:latest
        name: node-feature-discovery
        securityContext:
          privileged: true
